apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: fastapi-hello-app # Name of the deployment
spec:
  selector:
    matchLabels:
      app: fastapi-hello-app
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: fastapi-hello-app
    spec:
      containers:
        - name: fastapi-hello-app
          image: localhost:5000/fastapi-hello-app
# Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
# The port that the container is running on in the cluster
